name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: |
          cd /Frontend/cypress

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          project: cypress/e2e/home.cy.js